name: AndroidBuild
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: LoginPage

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: LoginPage

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: LoginPages.apk
          path: app/build/outputs/apk/debug/app-debug.apk
